USE SETHU
SELECT * FROM covid_testing_cleaned_updated

###Total tests per country
SELECT COUNTRY, COUNT(*) AS TOTAL_TEST FROM covid_testing_cleaned_updated
GROUP BY country

###Weekly average increase per country
SELECT COUNTRY, YEAR, WEEK, ROUND(AVG(DAILY_CHANGE_IN_CUMULATIVE_TOTAL),2) AS WEEKLY_AVG_INCREASE
FROM covid_testing_cleaned_updated
GROUP  BY country,YEAR,week
ORDER BY country,YEAR,week

###Top 5 countries with most testing per 1000 population
SELECT TOP 5 T.COUNTRY, MAX(T.CUMULATIVE_TOTAL) AS TOTAL_TESTS, P.POPULATION,
ROUND(MAX(T.CUMULATIVE_TOTAL)*1000.0/P.POPULATION,2) AS TESTS_PER_1000
FROM COVID_TESTING_CLEANED_UPDATED T
JOIN COUNTRY_POPULATION P ON T.COUNTRY = P.COUNTRY
WHERE T.CUMULATIVE_TOTAL IS NOT NULL
GROUP BY T.COUNTRY, P.POPULATION
ORDER BY TESTS_PER_1000 DESC

##Null-checks: Which countries have missing daily entries
SELECT COUNTRY, COUNT(*) AS MISSING_DATA FROM covid_testing_cleaned_updated
WHERE daily_change_in_cumulative_total IS NULL
GROUP BY COUNTRY ORDER BY MISSING_DATA DESC

###Latest cumulative total per country
WITH LATEST_ENTRIES AS (
SELECT COUNTRY, DATE,
CUMULATIVE_TOTAL,
ROW_NUMBER()OVER(PARTITION BY COUNTRY ORDER BY DATE DESC) AS RN
FROM covid_testing_cleaned_updated
WHERE CUMULATIVE_TOTAL IS NULL)
SELECT COUNTRY, DATE, CUMULATIVE_TOTAL FROM LATEST_ENTRIES
WHERE RN = 1 ORDER BY cumulative_total DESC